name: RuleKit
author: TheDragonRing
version: 0.0.1
description: A simple rules plugin
api: 2.0.0
main: TheDragonRing\RuleKit\Main
load: STARTUP
commands:
    rules:
        usage: /rules 1|2
        description: Shows server rules
permissions:
    rulekit.rules:
        default: true
        description: Allows use of /rules
